### ISSUE TITLE
how to publish a topic and message in controller?

### ISSUE THREAD

**Issue by hongshulin126** [rafiulgits/mqtt-client-dotnet-core#2]
how to publish a topic and message in controller?

**Comment by rafiulgits** [comment]
```C#
public class MyController : ControllerBase
{
    private readonly IMqttClientService mqttClientService;
    public MyController(MqttClientServiceProvider provider)
    {
        mqttClientService = provider.MqttClientService;
      // invoke mqttClientService methods and attribute
    }
}
```

**Way : 1**

make `mqttClient` attribute public to available for access

![image](https://user-images.githubusercontent.com/27845214/107600254-60f6ca00-6c4d-11eb-9106-c5ee4c296880.png)

***
**Way : 2**
Add a new method(s) `IMqttClientService` which will interpret with `mqttClient` method(s).  Just like `PublishToMqttAsync` to invoke `mqttClient.PublishAsync`
