### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by rafiulgits** [rafiulgits/mqtt-client-dotnet-core#5]
hey @quan0zhou as you upgrade the codebase with latest version of MQTT package, also you removed some classes. It would be great to update the README file as well so that other can use that project for their own purpose

**Comment by rafiulgits** [comment]
#4

**Comment by quan0zhou** [comment]
Ok, I'll try to change the readme file

**Comment by rafiulgits** [comment]
#6 fixed here
